//! Synthetic large-input ISO 20022 XML generator — a deliberate,
//! opt-in performance/scale tool (NOT product code, NOT run in the
//! dev loop / preflight / CI).
//!
//! ```text
//! cargo run --release --example gen_synthetic_xml -- <emir|sftr> <n> <out_path>
//! ```
//!
//! Emits an `auth.030.001.03` (EMIR) or `auth.052.001.02` (SFTR)
//! report with `n` `<Rpt><New>` records, **streamed** to the output
//! file (never holds `n` strings in memory). Deterministic and
//! index-driven (no RNG) so the same `n` yields byte-identical XML.
//! Records are richly populated so they round-trip the real
//! `opendqi-xml` parsers into non-empty `EmirRecord` / `SftrRecord`
//! and exercise the check loop non-trivially.
//!
//! Hand-authored — NOT derived from, and does not redistribute, any
//! ESMA or SWIFT example or schema. Only public ISO 20022 element
//! names + synthetic `OPENDQI-…` / `DUMMY…` values. Element shapes
//! mirror `examples/{emir,sftr}/iso20022/sample.xml`. The output is
//! written to a caller-supplied path (use a temp dir; never commit
//! generated data).

use std::fs::File;
use std::io::{BufWriter, Write};
use std::process::ExitCode;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().collect();
    if args.len() != 4 {
        eprintln!(
            "usage: gen_synthetic_xml <emir|sftr> <n> <out_path>\n\
             (deliberate opt-in scale tool — write to a temp dir, never commit the output)"
        );
        return ExitCode::FAILURE;
    }
    let regime = args[1].as_str();
    let n: usize = match args[2].parse() {
        Ok(v) => v,
        Err(_) => {
            eprintln!(
                "error: <n> must be a non-negative integer, got {:?}",
                args[2]
            );
            return ExitCode::FAILURE;
        }
    };
    let out_path = &args[3];

    let file = match File::create(out_path) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("error: cannot create {out_path}: {e}");
            return ExitCode::FAILURE;
        }
    };
    let mut w = BufWriter::new(file);

    let res = match regime {
        "emir" => write_emir(&mut w, n),
        "sftr" => write_sftr(&mut w, n),
        other => {
            eprintln!("error: regime must be `emir` or `sftr`, got {other:?}");
            return ExitCode::FAILURE;
        }
    };
    if let Err(e) = res.and_then(|()| w.flush()) {
        eprintln!("error: write failed: {e}");
        return ExitCode::FAILURE;
    }
    eprintln!("wrote {n} {regime} records → {out_path}");
    ExitCode::SUCCESS
}

const PROVENANCE: &str = "<!-- Synthetic large-input scale fixture generated by \
opendqi-core/examples/gen_synthetic_xml.rs. Hand-authored shapes — NOT derived from \
any ESMA/SWIFT example or schema; public ISO 20022 element names + synthetic values \
only. Do not commit. -->";

fn write_emir<W: Write>(w: &mut W, n: usize) -> std::io::Result<()> {
    const ASSET: &[&str] = &["RATE", "CRDT", "CURR", "EQUI", "COMM"];
    writeln!(w, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>")?;
    writeln!(w, "{PROVENANCE}")?;
    writeln!(
        w,
        "<Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:auth.030.001.03\">"
    )?;
    writeln!(w, "<DerivsTradRpt><TradData>")?;
    for i in 0..n {
        let asset = ASSET[i % ASSET.len()];
        let notional = (i as u64 + 1) * 1_000_000;
        let valn = notional / 100;
        let mat_month = (i % 12) + 1;
        write!(
            w,
            "<Rpt><New>\
<CtrPtySpcfcData>\
<NttyRspnsblForRpt><LEI>DUMMYERR0000000000AA</LEI></NttyRspnsblForRpt>\
<RptgCtrPty><Id><LEI>DUMMYCPTY100000000AA</LEI></Id><Ntr>F</Ntr>\
<TradgCpcty>PRIN</TradgCpcty><RptgOblgtn>true</RptgOblgtn></RptgCtrPty>\
<OthrCtrPty><Id><Org><LEI>DUMMYCPTY200000000AA</LEI></Org></Id></OthrCtrPty>\
</CtrPtySpcfcData>\
<CmonTradData>\
<CtrctData><AsstClss>{asset}</AsstClss><PdctClssfctn>SRACA</PdctClssfctn>\
<MstrAgrmt><Tp>ISDA</Tp><Vrsn>2002</Vrsn></MstrAgrmt><NtraGrpTx>false</NtraGrpTx></CtrctData>\
<TxData><TradId><UnqTxIdr>OPENDQI-GEN-{i:08}</UnqTxIdr></TradId>\
<EvtTp>TRAD</EvtTp>\
<ExctnTmStmp>2026-01-01T09:00:00Z</ExctnTmStmp>\
<EvtTmStmp>2026-01-01T10:00:00Z</EvtTmStmp>\
<RptgTmStmp>2026-01-01T18:00:00Z</RptgTmStmp>\
<EffctvDt>2026-01-15</EffctvDt>\
<MtrtyDt>2030-{mat_month:02}-15</MtrtyDt>\
<NtnlAmt><Lgs><FrstLgNtnl><Amt Ccy=\"EUR\">{notional}</Amt></FrstLgNtnl></Lgs></NtnlAmt>\
<Pric><Amt Ccy=\"EUR\">100.25</Amt></Pric></TxData>\
<Valtn><Amt Ccy=\"EUR\">{valn}</Amt><TmStmp>2026-05-13T08:00:00Z</TmStmp><Tp>MTMA</Tp></Valtn>\
<Coll><PrtflCd>PF-{:04}</PrtflCd><CollstnInd>FLCL</CollstnInd></Coll>\
<Clr><Clrd>true</Clrd><CCP><LEI>LCHLDNUS00000000AA</LEI></CCP></Clr>\
</CmonTradData></New></Rpt>",
            i % 50
        )?;
        writeln!(w)?;
    }
    writeln!(w, "</TradData></DerivsTradRpt></Document>")?;
    Ok(())
}

fn write_sftr<W: Write>(w: &mut W, n: usize) -> std::io::Result<()> {
    writeln!(w, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>")?;
    writeln!(w, "{PROVENANCE}")?;
    writeln!(
        w,
        "<Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:auth.052.001.02\">"
    )?;
    writeln!(w, "<SctiesFincgRptgTxRpt><TradData>")?;
    for i in 0..n {
        let principal = (i as u64 + 1) * 1_000_000;
        let coll = principal + 50_000;
        write!(
            w,
            "<Rpt><New>\
<CtrPtySpcfcData>\
<NttyRspnsblForRpt><LEI>ABCDEFGHIJKLMNOPQR01</LEI></NttyRspnsblForRpt>\
<RptgCtrPty><Id><LEI>ABCDEFGHIJKLMNOPQR02</LEI></Id></RptgCtrPty>\
<OthrCtrPty><Id><Org><LEI>ABCDEFGHIJKLMNOPQR03</LEI></Org></Id></OthrCtrPty>\
</CtrPtySpcfcData>\
<LnData><Repo>\
<UnqTxIdr>OPENDQI-GENSFT-{i:08}</UnqTxIdr>\
<EvtTp>NEWT</EvtTp>\
<ExctnDtTm>2026-04-01T09:00:00Z</ExctnDtTm>\
<RptgDtTm>2026-04-01T18:00:00Z</RptgDtTm>\
<SttlmDt>2026-04-02</SttlmDt>\
<EvntDt>2026-04-02</EvntDt>\
<MtrtyDt>2027-07-02</MtrtyDt>\
<PrncplAmt><Amt Ccy=\"EUR\">{principal}</Amt></PrncplAmt>\
<MstrAgrmt><Tp>GMRA</Tp><Vrsn>2011</Vrsn></MstrAgrmt>\
<RbtRate>0.0250</RbtRate>\
</Repo></LnData>\
<CollData>\
<CollVal><Amt Ccy=\"EUR\">{coll}</Amt></CollVal>\
<Hrcut>0.05</Hrcut>\
<AvlblForCollReuse>false</AvlblForCollReuse>\
<PrtflCd>SFTR-PF-{:04}</PrtflCd>\
<Sctys><Id>DE0001135275</Id></Sctys>\
</CollData></New></Rpt>",
            i % 50
        )?;
        writeln!(w)?;
    }
    writeln!(w, "</TradData></SctiesFincgRptgTxRpt></Document>")?;
    Ok(())
}
