[package]
name = "opendqi-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "OpenDQI IO: CSV ingestion, YAML mapping, file discovery."

[dependencies]
opendqi-core = { path = "../opendqi-core" }
anyhow.workspace = true
serde.workspace = true
serde_yaml.workspace = true
csv.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
tracing.workspace = true
walkdir.workspace = true
